# ----------------------------------------------------------------------------------------------------------------------
# Pyris base service
# ----------------------------------------------------------------------------------------------------------------------

services:
  pyris-app:
    container_name: pyris-app
    build:
      context: ..
      dockerfile: Dockerfile
      pull: true
    environment:
      APPLICATION_YML_PATH: "/config/application.yml"
      LLM_CONFIG_PATH: "/config/llm_config.yml"
    expose:
      - "8000"
    networks:
      - pyris
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

networks:
  pyris:
    driver: "bridge"
    name: pyris